Season.create!([Add commentMore actions
  {
    year: 2023,
    week: '1',
    gamedate: 'Sun 09/10',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '21 - 31',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '2',
    gamedate: 'Sun 09/17',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '31 - 20 ',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'NRG Stadium',
    map: 'https://maps.app.goo.gl/Rn65v4AKkgNgHQDr7'
  },
  {
    year: 2023,
    week: '3',
    gamedate: 'Sun 09/24',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '22 - 19',
    oppcity: 'Baltimore',
    oppname: 'Ravens',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/bal.png&h=200&w=200',
    stadium: 'M&T Bank Stadium',
    map: 'https://maps.app.goo.gl/Td2KScyke6YF4rj9A'
  },
  {
    year: 2023,
    week: '4',
    gamedate: 'Sun 10/01',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '23 - 29',
    oppcity: 'Los Angeles',
    oppname: 'Rams',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lar.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '5',
    gamedate: 'Sun 10/08',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '23 - 16',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '6',
    gamedate: 'Sun 10/15',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '20 - 37',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Everbank Stadium',
    map: 'https://maps.app.goo.gl/UTR1xnoTcK1bAGtK9'
  },
  {
    year: 2023,
    week: '7',
    gamedate: 'Sun 10/22',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '38 - 39',
    oppcity: 'Cleveland',
    oppname: 'Browns',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cle.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '8',
    gamedate: 'Sun 10/29',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '27 - 38',
    oppcity: 'New Orleans',
    oppname: 'Saints',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/no.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '9',
    gamedate: 'Sun 11/05',
    gametime: '4:05PM',
    location: 'away',
    result: 'W',
    score: '27 - 13',
    oppcity: 'Carolina',
    oppname: 'Panthers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/car.png&h=200&w=200',
    stadium: 'Bank of America Stadium',
    map: 'https://maps.app.goo.gl/fh1A1RGx3AvJzhcdA'
  },
  {
    year: 2023,
    week: '10',
    gamedate: 'Sun 11/12',
    gametime: '9:30AM',
    location: 'away',
    result: 'W',
    score: '10 -  6',
    oppcity: 'New England',
    oppname: 'Patriots',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png&h=200&w=200',
    stadium: 'Deutsche Bank Park',
    map: 'https://maps.app.goo.gl/PaMFTEi8Dj2wFBYT8'
  },
  {
    year: 2023,
    week: '11',
    oppname: 'Bye'
  },
  {
    year: 2023,
    week: '12',
    gamedate: 'Sun 11/26',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '20 -  27',
    oppcity: 'Tampa Bay',
    oppname: 'Buccaneers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/tb.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '13',
    gamedate: 'Sun 12/03',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '31 -  28',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Nissan Stadium',
    map: 'https://maps.app.goo.gl/4ptMhmc13gTWMYri7'
  },
  {
    year: 2023,
    week: '14',
    gamedate: 'Sun 12/10',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '14 - 34',
    oppcity: 'Cincinnati',
    oppname: 'Bengals',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cin.png&h=200&w=200',
    stadium: 'Paycor Stadium',
    map: 'https://maps.app.goo.gl/r72zDuZE8yskC4mYA'
  },
  {
    year: 2023,
    week: '15',
    gamedate: 'Sat 12/16',
    gametime: '4:30PM',
    location: 'home',
    result: 'W',
    score: '30 - 13',
    oppcity: 'Pittsburgh',
    oppname: 'Steelers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '16',
    gamedate: 'Sun 12/24',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '10 - 29',
    oppcity: 'Atlanta',
    oppname: 'Falcons',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/atl.png&h=200&w=200',
    stadium: 'Mercedes - Benz Stadium',
    map: 'https://maps.app.goo.gl/fXoJJ1LqZDmyNbDD7'
  },
  {
    year: 2023,
    week: '17',
    gamedate: 'Sun 12/31',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '23 - 20',
    oppcity: 'Las Vegas',
    oppname: 'Raiders',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lv.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2023,
    week: '18',
    gamedate: 'Sat 01/06',
    gametime: '8:15PM',
    location: 'home',
    result: 'L',
    score: '19 - 23',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '1',
    gamedate: 'Sun 09/07',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Miami',
    oppname: 'Dolphins',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/mia.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/Td2KScyke6YF4rj9A'
  },
  {
    year: 2024,
    week: '2',
    gamedate: 'Sun 09/15',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '10 - 16',
    oppcity: 'Green Bay',
    oppname: 'Packers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/gb.png&h=200&w=200',
    stadium: 'Lambeau Field',
    map: 'https://maps.app.goo.gl/49a4HGaCSfsR6KFWA'
  },
  {
    year: 2024,
    week: '3',
    gamedate: 'Sun 09/22',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '21 - 16',
    oppcity: 'Chicago',
    oppname: 'Bears',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/chi.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '4',
    gamedate: 'Sun 09/29',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '27 - 24',
    oppcity: 'Pittsburgh',
    oppname: 'Steelers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '5',
    gamedate: 'Sun 10/06',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '34 - 37',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Everbank Stadium',
    map: 'https://maps.app.goo.gl/UTR1xnoTcK1bAGtK9'
  },
  {
    year: 2024,
    week: '6',
    gamedate: 'Sun 10/13',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '20 - 17',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Nissan Stadium',
    map: 'https://maps.app.goo.gl/4ptMhmc13gTWMYri7'
  },
  {
    year: 2024,
    week: '7',
    gamedate: 'Sun 10/20',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '16 - 10',
    oppcity: 'Miami',
    oppname: 'Dolphins',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/mia.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '8',
    gamedate: 'Sun 10/27',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '20 - 23',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'NRG Stadium',
    map: 'https://maps.app.goo.gl/Rn65v4AKkgNgHQDr7'
  },
  {
    year: 2024,
    week: '9',
    gamedate: 'Sun 11/03',
    gametime: '8:20PM',
    location: 'away',
    result: 'L',
    score: '13 - 21',
    oppcity: 'Minnesota',
    oppname: 'Vikings',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/min.png&h=200&w=200',
    stadium: 'U.S. Bank Stadium',
    map: 'https://maps.app.goo.gl/m3Qb2PHXte6YpMjJ8'
  },
  {
    year: 2024,
    week: '10',
    gamedate: 'Sun 11/10',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '20 - 30',
    oppcity: 'Buffalo',
    oppname: 'Bills',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/buf.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '11',
    gamedate: 'Sun 11/17',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '28 - 27',
    oppcity: 'New York',
    oppname: 'Jets',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyj.png&h=200&w=200',
    stadium: 'MetLife Stadium',
    map: 'https://maps.app.goo.gl/fkHqdH8JK7SaQQgr8'
  },
  {
    year: 2024,
    week: '12',
    gamedate: 'Sun 11/24',
    gametime: '1:00PM',
    location: 'home',
    result: 'L',
    score: '6 - 24',
    oppcity: 'Detroit',
    oppname: 'Lions',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/det.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '13',
    gamedate: 'Sun 12/01',
    gametime: '1:00PM',
    location: 'away',
    result: 'W',
    score: '25 - 24',
    oppcity: 'New England',
    oppname: 'Patriots',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png&h=200&w=200',
    stadium: 'Gillette Stadium',
    map: 'https://maps.app.goo.gl/WpjNgrxqz4rJdMyv8'
  },
  {
    year: 2024,
    week: '14',
    oppname: 'Bye'
  },
  {
    year: 2024,
    week: '15',
    gamedate: 'Sat 12/15',
    gametime: '4:25PM',
    location: 'away',
    result: 'L',
    score: '13 - 31',
    oppcity: 'Denver',
    oppname: 'Broncos',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/den.png&h=200&w=200',
    stadium: 'Empower Field at Mile High',
    map: 'https://maps.app.goo.gl/tYWXfkvTtLpyM5k57'
  },
  {
    year: 2024,
    week: '16',
    gamedate: 'Sun 12/22',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '38 - 30',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2024,
    week: '17',
    gamedate: 'Sun 11/29',
    gametime: '1:00PM',
    location: 'away',
    result: 'L',
    score: '33 - 45',
    oppcity: 'New York',
    oppname: 'Giants',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyg.png&h=200&w=200',
    stadium: 'MetLife Stadium',
    map: 'https://maps.app.goo.gl/fkHqdH8JK7SaQQgr8'
  },
  {
    year: 2024,
    week: '18',
    gamedate: 'Sun 01/05',
    gametime: '1:00PM',
    location: 'home',
    result: 'W',
    score: '26 - 23',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6'
  },
  {
    year: 2025,
    week: '1',
    gamedate: 'Sun 09/07',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Miami',
    oppname: 'Dolphins',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/mia.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '2',
    gamedate: 'Sun 09/14',
    gametime: '4:05PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Denver',
    oppname: 'Broncos',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/den.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '3',
    gamedate: 'Sun 09/21',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Nissan Stadium',
    map: 'https://maps.app.goo.gl/4ptMhmc13gTWMYri7'
  },
  {
    year: 2025,
    week: '4',
    gamedate: 'Sun 09/28',
    gametime: '4:05PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Los Angeles',
    oppname: 'Rams',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lar.png&h=200&w=200',
    stadium: 'SoFi Stadium',
    map: 'https://maps.app.goo.gl/iXXVb5WpnrazZPpm8'
  },
  {
    year: 2025,
    week: '5',
    gamedate: 'Sun 10/05',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Las Vegas',
    oppname: 'Raiders',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lv.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '6',
    gamedate: 'Sun 10/12',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Arizona',
    oppname: 'Cardinals',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ari.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '7',
    gamedate: 'Sun 10/19',
    gametime: '4:05PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Los Angeles',
    oppname: 'Chargers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/lac.png&h=200&w=200',
    stadium: 'SoFi Stadium',
    map: 'https://maps.app.goo.gl/iXXVb5WpnrazZPpm8'
  },
  {
    year: 2025,
    week: '8',
    gamedate: 'Sun 10/26',
    gametime: '4:25PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Tennessee',
    oppname: 'Titans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '9',
    gamedate: 'Sun 11/02',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Pittsburgh',
    oppname: 'Steelers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png&h=200&w=200',
    stadium: 'Acrisure Stadium',
    map: 'https://maps.app.goo.gl/KrZ3iqwyfuduCiXw7'
  },
  {
    year: 2025,
    week: '10',
    gamedate: 'Sun 11/09',
    gametime: '9:30AM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Atlanta',
    oppname: 'Falcons',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/atl.png&h=200&w=200',
    stadium: 'Olympic Stadium',
    map: 'https://maps.app.goo.gl/RhJ3uc8mHThy4w8r7'
  },
  {
    year: 2025,
    week: '11',
    oppname: 'Bye',
  },
  {
    year: 2025,
    week: '12',
    gamedate: 'Sun 11/23',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Kansas City',
    oppname: 'Chiefs',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/kc.png&h=200&w=200',
    stadium: 'Arrowhead Stadium',
    map: 'https://maps.app.goo.gl/GdA5S7zrgTa3nTn18'
  },
  {
    year: 2025,
    week: '13',
    gamedate: 'Sun 11/30',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '14',
    gamedate: 'Sun 12/07',
    gametime: '1:00PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Everbank Stadium',
    map: 'https://maps.app.goo.gl/UTR1xnoTcK1bAGtK9'
  },
  {
    year: 2025,
    week: '15',
    gamedate: 'Sun 12/14',
    gametime: '4:25PM',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Seattle',
    oppname: 'Seahawks',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sea.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/9rRk2X4Hnmq99L468'
  },
  {
    year: 2025,
    week: '16',
    gamedate: 'Mon 12/22',
    gametime: '8:15PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'San Francisco',
    oppname: '49ers',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sf.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '17',
    gamedate: 'Sun 12/28',
    gametime: '1:00PM',
    location: 'home',
    result: '',
    score: '',
    oppcity: 'Jacksonville',
    oppname: 'Jaguars',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png&h=200&w=200',
    stadium: 'Lucas Oil Stadium',
    map: 'https://maps.app.goo.gl/4Jk41ViV5SnsFgBR6A'
  },
  {
    year: 2025,
    week: '18',
    gamedate: 'TBD',
    gametime: 'TBD',
    location: 'away',
    result: '',
    score: '',
    oppcity: 'Houston',
    oppname: 'Texans',
    oppimage: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png&h=200&w=200',
    stadium: 'NRG Stadium',
    map: 'https://maps.app.goo.gl/Rn65v4AKkgNgHQDr7'
  }
])